---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: sample_node
- name: current-app-info

outputs:
- name: app-manifest-output

run:
  path: sample_node/blue-green-app-deployment/ci/tasks/app-manifest-prep
