---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: sample_node

outputs:
- name: current-app-info

run:
  path: sample_node/blue-green-app-deployment/ci/tasks/current-app-get-info
